# Generated by Django 3.0.8 on 2020-07-30 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(db_column='collaborate_messaging_a00_rec', primary_key=True, serialize=False)),
                ('message_content', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('group_id', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_post_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='post_comment.Message')),
            ],
        ),
    ]
